const language = {
    header: {
        en: {
            header_index: "Home",
            header_references: "References",
            header_about: "About",
            header_projects: "Projects",
            header_contact: "Contact",
        },
        no: {
            header_index: "Hjem",
            header_references: "Referanser",
            header_about: "Om oss",
            header_projects: "Prosjekter",
            header_contact: "Kontakt oss",
        },
    },
    footer: {
        en: {
            adress_header: "Visit us",
            adress_desc: "Professor Brochs Gate 8A, 7030, Trondheim",
            email_header: "Write us",
            email_desc: "kontakt@norskdatateknikk.no",
            phone_header: "Call us",
            phone_desc: "+47 908 11 303",
        },
        no: {
            adress_header: "Besøk oss",
            adress_desc: "Professor Brochs Gate 8A, 7030, Trondheim",
            email_header: "Skriv til oss",
            email_desc: "kontakt@norskdatateknikk.no",
            phone_header: "Ring oss",
            phone_desc: "+47 908 11 303",
        },
    },
    index: {
        en: {
            index_header: "Do you need assistance with electronics?",
            index_btn: "Contact us >>",
            index_2_header: "Our projects",
            index_2_desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id.",
            index_3_header: "What we can do",
            index_3_1_header: "Systems",
            index_3_1_desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id.",
            index_3_2_header: "Instrumentation",
            index_3_2_desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id.",
            index_3_3_header: "Radio",
            index_3_3_desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id.",
            index_3_4_header: "Programming",
            index_3_4_desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id.",
            index_4_header: "Our process",
        },
        no: {
            index_header: "Trenger du elektronikkhjelp?",
            index_btn: "Kontakt oss >>",
            index_2_header: "Vi kan hjelpe deg!",
            index_2_desc: "Norsk Datateknikk AS tilbyr rådgivnings- og utviklingstjenester innenfor elektronikk, blant annet tilpassede elektroniske og innvevde systemer med fokus på kvalitet og pålitelighet.",
            index_3_header: "Hva vi kan",
            index_3_1_header: "Systemer",
            index_3_1_desc: "Fra kretskort til programvare, vi hjelper deg med å utvikle systemene du trenger, inkludert innkapsling, produksjon og sammenstilling.",
            index_3_2_header: "Instrumentering",
            index_3_2_desc: "Vi kan hjelpe deg med å måle det du ønsker å måle gjennom spesialtilpassede sensorsystemer med tilhørende signalbehandling.",
            index_3_3_header: "Radioteknikk",
            index_3_3_desc: "Enten det er trådløs kommunikasjon, antennedesign eller «compliance testing» så kan vi bistå deg med utvikling og rådgivning.",
            index_3_4_header: "Programmering",
            index_3_4_desc: "Med kompetanse i C, C++, Python og LabView kan vi bistå deg i programmering av blant annet sanntidssystemer og maskinlæringssystemer.",
            index_4_header: "Vår prosess",
        },
    },
    about: {
        en: {
            about_heading: "About",
            about_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id. Donec faucibus urna non ligula imperdiet tristique.",

            person1_heading: "Erik Hole",
            person1_position: "Managing Director, project Engineer",
            person1_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id. Donec faucibus urna non ligula imperdiet tristique. Nunc ut urna eget sem venenatis egestas.",
            person1_email: "erik.hole@norskdatateknikk.no",

            person2_heading: "Erik Buer",
            person2_position: "Technical director, system architecht",
            person2_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id. Donec faucibus urna non ligula imperdiet tristique. Nunc ut urna eget sem venenatis egestas.",
            person2_email: "erik.buer@norskdatateknikk.no",

            person3_heading: "Mikolaj Jaworski",
            person3_position: "Software engineer",
            person3_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id. Donec faucibus urna non ligula imperdiet tristique. Nunc ut urna eget sem venenatis egestas.",
            person3_email: "mikolaj.jaworski@norskdatateknikk.no",

            person4_heading: "Anders Nilsen",
            person4_position: "Software engineer",
            person4_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id. Donec faucibus urna non ligula imperdiet tristique. Nunc ut urna eget sem venenatis egestas.",
            person4_email: "anders.nilsen@norskdatateknikk.no",
        },
        no: {
            about_heading: "Om oss",
            about_description: "Norsk Datateknikk AS ble grunnlagt i november 2018 av fire venner i løpet som resultat av dagdrømming i lunsjpausene på NTNU. Vi er lokalisert i Teknobyen på Elgeseter i Trondheim.",

            person1_heading: "Erik Hole",
            person1_position: "Daglig leder, prosjektingeniør",
            person1_description: "Erik er firmaets daglige leder, men jobber samtidig som prosjektingeniør. Med en bachelor og master innenfor instrumenteringsteknikk er han firmaets instrumenteringsspesialist i tillegg til å bistå med kompetanse innenfor mekanikk, analogteknikk og fiberteknikk.",
            person1_email: "erik.hole@norskdatateknikk.no",

            person2_heading: "Erik Buer",
            person2_position: "Teknisk direktør, systemarkitekt",
            person2_description: "Erik er firmaets tekniske direktør og systemarkitekt. Han er ansvarlig for prosessene i firmaet, men er og firmaets ekspert på analog- og radioteknikk, med en bachelor i elektronikk og erfaring fra Kongsberg.",
            person2_email: "erik.buer@norskdatateknikk.no",

            person3_heading: "Mikolaj Jaworski",
            person3_position: "Signalbehandlingsingeniør",
            person3_description: "Med utdannelse innenfor elektronikk og akustikk er Mikolaj teamets signalbehandlingsekspert og akustiker. I tillegg bidrar han med kunnskap innenfor programmering og sammenstilling av elektronikk.",
            person3_email: "mikolaj.jaworski@norskdatateknikk.no",

            person4_heading: "Anders Nilsen",
            person4_position: "Programvareingeniør",
            person4_description: "Anders er teamets programmerer og digitaldesigner. Med bachelor i automatiseringsteknikk og master i innvevde systemer fra NTNU er Anders ansvarlig for utviklingen av sanntidssystemer i bedriften.",
            person4_email: "anders.nilsen@norskdatateknikk.no",
        },
    },
    contact: {
        en: {
            contact_header: "Contact us",
            contact_form: "Contact form",
            contact_name: "Name",
            contact_email: "E-mail",
            contact_subject: "Subject",
            contact_message: "Message",

        },
        no: {
            contact_header: "Kontakt oss",
            contact_form: "Kontaktskjema",
            contact_name: "Navn",
            contact_email: "E-mail",
            contact_subject: "Emne",
            contact_message: "Melding",
        },
    },
    projects: {
        en: {
            projects_heading: "Projects",
            projects_desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            projects_imageheader_1: " Integer eu maximus nisl. Mauris condimentum, magna condimentum.",
            projects_imageheader_2: "lorem lorem laoreet sem, ut tempus nulla diam a turpis.",
            projects_imageheader_3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            projects_imageheader_4: "Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id.",
        },
        no: {
            projects_heading: "Prosjekter",
            projects_desc: "Her er et utvalg av prosjekter som vi har jobbet med enten for kunder eller internt:",
            projects_imageheader_1: "Håndholdt kamera for bruk i slitasjetesting av lastebiler.",
            projects_imageheader_2: "Oppgradering av strømforsyning og UPS for statuslogger for skip.",
            projects_imageheader_3: "Håndholdt kamera for bruk i slitasjetesting av lastebiler.",
            projects_imageheader_4: "Oppgradering av strømforsyning og UPS for statuslogger for skip.",
        },
    },
    references:{
        en: {
            references_heading: "References",
            references_desc: "Our previous collaboration has produced good results",
            references1_name: "TECNEC ELECTRONICS AS",
            references1_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id." ,
            references_link_1: "www.tecnec.no",
            references2_name:"LANGØ SERVICE AS",
            references2_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim lobortis lorem, ac vestibulum orci scelerisque id. Donec faucibus urna non ligula imperdiet tristique. Nunc ut urna eget sem venenatis egestas.",
            references_link_2: "www.lango-service.no",
        },
        no: {
            references_heading: 'Våre referanser',
            references_desc: 'Våre tidligere samarbeid har gitt gode resultater.',
            references1_name: "TECNEC ELECTRONICS AS",
            references1_description: "Tecnec Electronics AS er et Trondheimsbasert firma som leverer konsulenttjenester innen elektronikkutvikling og -produksjon. ",
            references_link_1: "www.tecnec.no",
            references2_name:"LANGØ SERVICE AS",
            references2_description: "Langø Service AS er en ledende leverandør innen utstyr til verksteder for tungtransport. Langø er Skandinavias største leverandør av prefabrikkerte graver, og produserer i tillegg tilhørende utstyr som bremsetestere og løfteutstyr.",
            references_link_2: "www.lango-service.no",
        },
    },
};
